### ISSUE TITLE
Map starts ignoring touch inputs at random intervals

### ISSUE THREAD

**Issue by Topener** [appcelerator-modules/ti.map#112]
I've got an issue with the latest version(s) that the map starts ignoring user inputs (zooming/scrolling/clicking) at random times. This happens in 2.3.1 and 2.3.2 on iOS.

This doesn't happen in 2.2.2, but I am not able to revert version as 2.3 offers circles...

**Comment by hansemannn** [comment]
Hi @Topener, does everything works in the latest version? Me made some related changes in the last months.

**Comment by yozef** [comment]
It could be that you have lots of overlays: such as polygons &/or circles &/polylines, the implementation of map click events when these were added creates a loop through all of them killing performance in order to return the overlay that was tapped on. I have compiled my own ti.map to remove these loops, as I did not need in my case to know which overlay was tapped on.

**Comment by Topener** [comment]
It was a map without any markers or overlays, and happend suddenly. However, this problem only occurred in combination with an older TiSDK and it was fixed by using 4 or higher.

**Comment by hansemannn** [comment]
Thanks! Closing this issue then.
