### ISSUE TITLE
Support Image Overlays for iOS and Android

### ISSUE THREAD

**Issue by simonhume** [appcelerator-modules/ti.map#136]
I use a 3rd party module for iOS (and Android, though it has never worked) to overlay images on top of native maps. Unfortunately, the module is quite old and doesn't work with the latest Titanium SDK.

Can we get support for native image overlay (like you added vector overlay support) too, you'd make a Zoo in the UK very happy indeed!

**Comment by ashcoding** [comment]
@simonhume I like Zoos. 

a) Which 3rd party module were u using? It might be easy enough to convert it to a Titanium Module.

b) By image overlay, which api are you referring to? https://developers.google.com/maps/documentation/android-api/intro

**Comment by simonhume** [comment]
@ashcoding OK, so I was using this module:

https://github.com/NetFunctional/ti.map

I did try and update it in xCode but got in a right old mess.

The basic idea behind it, is that you declare a Top left and Bottom right position for the image overlay (in my case a PNG of the Zoo map) to sit over the top.

Annotations are then plotted on top as normal and the user can zoom in and out.

That module has an Android version, but I never had it working at all, where as the iOS one did work previously.

In terms of the Android API, I 'assume' it would be this.......

https://developers.google.com/maps/documentation/android-api/groundoverlay

**Comment by ashcoding** [comment]
A ticket for this https://jira.appcelerator.org/browse/MOD-2173 has been created by @hansemannn

**Comment by simonhume** [comment]
thanks @ashcoding, how long do these normally take to reach a release?

**Comment by ashcoding** [comment]
A jira ticket normally gets pushed for development when there's lots of watchers and/or there's a bug.

This issue is a request for improvement. It would move faster if a PR is submitted for review.

**Comment by jabele** [comment]
@ashcoding Do you have a sample PR that is in a format that would be helpful for this project? I would be happy to create this to get it moving through the pipeline.

**Comment by eckoj433** [comment]
We are currently using a webview to access the javascript api of googlemaps, in order to be able to use the groundOverlay functionality. However running googlemaps in a webview is far from the best experience for the user, and it would be GREATLY appriciated if this functionality could be added. Especially for android sence running googlemaps in a webview is considerably slower/laggy on android than iOS.

**Comment by asiby** [comment]
Hi guys

I have read all the messages but I'm still not sure about what @simonhume needs. To be honest, I'm no longer sure about what an overlay is after having seen different experts referring to different things as being "overlays".

I have added a new feature that may or may not be what you are looking for. It allows the following on Android (iOS will come later). The following assumes that the MapView instance is called mapView:

1 -  Adding a property to the MapView object that we called `mapView.customTileSourceUrl`

2 - The `mapView.customTileSourceUrl` can be set using one of the following ways:

> - At creation time like this ... `Map.createView({ ..., customTileSourceUrl: "http://..." ... })`.
> - As property using a standard assignment like ... ` ... mapView.customTileSourceUrl = "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png/";`
> - As property using a setter like ... ` ... mapView.setCustomTileSourceUrl("https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png/");`
> - Using `mapView.applyProperties({...});`

3 - After setting this property, the default GoogleMap base layer will never be shown and your custom tiles will be the one being used. You just need make sure that the proper zoom level and region are set so that you can actually see your tiles. 

4 - Your tiles do not have the cover the entire planet. In that case, you can also pass 4 bound parameters to limit how far someone can pan the map around if your map is not covering the entire planet.

5 - You can pass a minZoom and maxZoom if your tile source provides a limited range of zoom levels.

6 - Finally, this is unrelated but I have added the ability to handle the GoogleMap event called onInfoWindowClose so that the app can react when the info window is closed. That was required in order to mitigate a bug that we discovered in Ti.Map. Another thread will be create soon for that.

These enhancements will not keep the current base layer and add a fixes overlay. Instead, this method will replace the base layer entirely. Though it is possible to use the concepts I used in order to achieve more complexe scenarios.

I am ironing up some of the corners before sending a PR as I recently discovered that if the customTileSourceUrl is not specified, then the base layer not disappears totally ... Oops. I just need to wrap some conditions around some lines of codes.

**Comment by ashcoding** [comment]
@asiby That sounds like awesome work!! Looking forward to it.

**Comment by yozef** [comment]
@asiby +1

**Comment by hansemannn** [comment]
@asiby I don't like the way to have the overlay as part of the mapView proxy. Instead, we should think of an interface design like this (feedback appreciated):
```javascript
var overlay = maps.createTile({
    url: "https://maps.wikimedia.org/osm-intl/{z}/{x}/{y}.png",
    // Other configurations if necessary ...
});
mapView.addTile(overlay);
```
@ashcoding, @yozef, @simonhume Thoughts?

**Comment by yozef** [comment]
I agree @hansemannn this way seems more manageable to reference Tiles independently (such removing one tile for example, and leaving the others). It seems to be the way GoogleMaps does it too.

**Comment by simonhume** [comment]
@hansemannn I'm not entirely sure the solution suggested covers my original request.

Tile overlays are one thing, but that is already offered by Mapbox. 

My request is part of the SDK as far as I know, so tiling really probably should be a different ticket to this one.

Did anyone check out the module I mentioned in my original request? That should give some clues as to how to achieve the image overlay with the tiling.

A separate tiling option would be amazing too!

**Comment by asiby** [comment]
Thanks for the suggestion. The custom tile provider that I have added is not in the view proxy. The only part of the view proxy that is having anything to do with the custom tile provider is the properties declarations like in the following code ...
```
@Kroll.proxy(creatableInModule = MapModule.class, propertyAccessors = {
		TiC.PROPERTY_USER_LOCATION, MapModule.PROPERTY_USER_LOCATION_BUTTON,
		TiC.PROPERTY_MAP_TYPE, TiC.PROPERTY_REGION, TiC.PROPERTY_ANNOTATIONS,
		TiC.PROPERTY_ANIMATE, MapModule.PROPERTY_TRAFFIC,
		TiC.PROPERTY_ENABLE_ZOOM_CONTROLS,
		MapModule.PROPERTY_COMPASS_ENABLED,
		MapModule.PROPERTY_CUSTOM_TILE_SOURCE_URL,   // <---- This
		MapModule.PROPERTY_CUSTOM_MIN_ZOOM,    // <---- This
		MapModule.PROPERTY_CUSTOM_MAX_ZOOM,   // <---- This
		MapModule.PROPERTY_CUSTOM_SOUTH_BOUND,    // <---- This
		MapModule.PROPERTY_CUSTOM_WEST_BOUND,   // <---- This
		MapModule.PROPERTY_CUSTOM_NORTH_BOUND,    // <---- This
		MapModule.PROPERTY_CUSTOM_EAST_BOUND })    // <---- This
```

The entire code in is the TiUIMapView. I don't see where else it should go.

On the other hand, in my opinion, the use case that you have shown will be great when adding actual overlays. But for base tiles, or for the only base tile, I assumed that having it done while the map is being initialized it far more efficient especially when you do not what to see the original Google base title for a brief moment while the map is loading.

I am open to any suggestions. But I would like to left you guys try what I did so that we can decide together where and how we want to take it to the next step.

Also, keep in mind that the naming conventions that I used can be totally changed for something more suitable.

I am currently struggling with the calculations and repositioning that will gracefully keep the map restricted to a given bounding box given the coverage area of the custom tiles. If any one of you feel comfortable with that aspect, than your help will be very welcome. I will commit these changes in the develop branch on my fork of Ti.Map if you feel like you can help in that regard.

Once the changes are stable enough I will merge them in the master branch then create a PR. I am basically using the Git Flow pattern.

**Comment by asiby** [comment]
@simonhume, if the module that you had referenced was doing exactly what you were looking for, then it may be worth seeing if it is in a state that can be adapted to the current version of Ti.Map.

**Comment by asiby** [comment]
To add to my previous [post](https://github.com/appcelerator-modules/ti.map/issues/136#issuecomment-213565268), here is a suggestion that can be used based on the suggestion from @hansemannn.

The making so that when we add a tile using .createTile() or .addTile(), we can specify if a particular tile is to be seen as a base tile source, which will clear set the mapType to MAP_TYPE_NONE). Without that, they will be simply overlaid on top of the existing things.

Using MapBox and Leaflet, I have seen cases when people could have multiple optional base tiles and multiple additional overlays. So we have to decide where to stop and create a minimum viable iteration that can be built upon. Check them out ...

Overlay examples:
- Example with an image overlay: https://www.mapbox.com/mapbox.js/example/v1.0.0/imageoverlay-georeferenced/
- Example with another type of image overlays: https://www.mapbox.com/mapbox.js/example/v1.0.0/inset-hawaii-alaska/
- More advanced types of overlays: https://www.mapbox.com/mapbox.js/example/v1.0.0/cycle-overlays/

Base layer or Base tile examples
- https://www.mapbox.com/mapbox.js/example/v1.0.0/toggle-baselayers/ (in this example, use the menu to toggle the base tiles)
- https://www.mapbox.com/mapbox.js/example/v1.0.0/external-layers/

I am just giving there examples to clarify the difference between handling the baselayer and additional overlays.

**Comment by asiby** [comment]
I have push some changed in my develop branch if anyone wants to take a look. It's at https://github.com/asiby/ti.map/tree/develop

I still need to update the module's example to include a sample usage of the new features.

**Comment by rlarmore** [comment]
Asiby, I've look at the code and it looks good. I haven't tried it yet but I'm excited to see it go into the main branch, any ETA? Also, any ideas on getting this to also work on apple maps for iphone?

**Comment by jabele** [comment]
Asiby, Thanks for putting this together. Have you had a chance to send a pull request yet? Just checking on the status of your fix. Thanks from the entire community!

**Comment by asiby** [comment]
Oh, you are welcome. I have been so busy lately that it took my mind totally off of this. Sorry about that. I have actually improve it even further by using the new Google Map API capabilities regarding limiting the bounds and the zoom when the use is using the map. Google finally listened. It's amazing to see that they do care about our feedback.

That new Google API will allow me to remove some mess that I had in there to try to limit the zoom and bound.

I will do my best to send a PR ASAP.

Thank guys for your patience.

**Comment by jabele** [comment]
I have been trying to test this by replacing out the Ti.Map module with what is in your current pull request but can't seem to replicate an example based on your current version. Is there any chance you could post a quick example code for how to test this overlay functionality? Let me know if there is anything else I can do to expedite this request. Thanks!

**Comment by rlarmore** [comment]
Asiby, wanted to follow up. Did you get a chance to update the PR? Thanks!

**Comment by asiby** [comment]
Hello rlarmore. I am in the process of doing it. However, I am having a
problem due to the API version that is in the module's manifest file. I am
having issues compiling if I leave it to apiversion 3. I have to bring it
down to 2 which sounds obviously wrong because progress always goes forward
and not backward.

Does anyone know what I might be missing. An update of something maybe? I
am confused by Titanium at this point. I have been fighting with this for
almost a week now.

Any help is appreciated. It's the only thing preventing me from compiling
my changes against the new Google SDK that is now part of the module and
submitting my PR.

Thanks

**Comment by hansemannn** [comment]
@asiby skypanther.com/2016/10/rebuilding-modules-for-titanium-6/

**Comment by rlarmore** [comment]
It would be nice to have a version 2 that support Ti 5.x since all of us are not on Ti6 yet. From my side I will have to wait until I am able to replace or find updates to all my 3rd party modules. Which may take some time.

**Comment by asiby** [comment]
Thank you so much Hans. This link is very useful.

Good point @rlarmore. I was using Ti 5.4.0.GA, but I have just updated the
SDK to 5.5.1.GA. I am not going to use 6. It's not released yet and all the
deadlines I am working against are for production releases. For that reason
I can't rely of Ti SDKs that are not officially released.

**Comment by asiby** [comment]
@hansemannn, I have just checked the link you have sent, and no matter what I do, as long as apiverison is 3, the module does not show up when trying to install it in any app using the latest stable SDK 5.5.1.GA.

That leads me to the following suggestion... Can we create an extra branch that will be dealing with the major version that this module is targeting? Without that, there is always going to be conflicting commits. The pull request that I am trying to send it going to effectively bringing the apiversion back to 2 and the minsdk down from 6.0.0... to 5.5.1.GA. That kind of scenario can keep going forever until version 6.0.0.GA is released. 

Also, how many other iterations of Ti SDK 5.x.x is going to happen being version 6 is out?

We can't loose our changes for the sake of SDK 6.0.0 because unfortunately we have to deal with the present and with out current apps that are on the market. And now that I know that apiversion 3 has breaking changes, I will soon have a local git branch that will deal with that.

Any thought?

BTW. The changes that I am trying to send are Android only for the moment. I will add them to the iOS version unless someone wants to tackle that part.

Thank you all.

**Comment by rlarmore** [comment]
Asiby,  haven't heard anything for some time. Did you get past this issue?

**Comment by asiby** [comment]
Nope. I didn't get any answer.

**Comment by hansemannn** [comment]
Cleaning up our ti.map issues to have a centralized discussion in JIRA. Can you follow [MOD-2145](https://jira.appcelerator.org/browse/MOD-2145) for further discussions. Thx!
