### ISSUE TITLE
Feature request: Tinting annotation images (will pay)

### ISSUE THREAD

**Issue by bitfabrikken** [appcelerator-modules/ti.map#155]
Hi, I'd really like to see a new feature where it's possible to supply a tint colour when you create an annotation with a custom image - on both iOS and Android.

If I find someone to do this, I will of course release it here as a pull request.

Anyone up for the challenge, or anyone also interested in this feature?

**Comment by hansemannn** [comment]
Hey there! Are there native API's for that? From what I know, we support:
- Tinting on Buttons (iOS), so you can say `.toImage()` and supply the blob in the `Annotation.image` property
- Tinting on ImageViews (Android) and supply it directly. I asked @m1ga who made that great PR to also support it for Buttons so we have parity with iOS, maybe he finds the time!

But that should get you started. Since it's no map-specific, I think both iOS and Android won't supply that options. Thanks!

**Comment by m1ga** [comment]
Tinting for Android buttons: https://github.com/appcelerator/titanium_mobile/pull/7924

**Comment by hansemannn** [comment]
@bitfabrikken are you fine with this solutions? Since it's a general thing, it can only be added in the annotation source (button / image / view) itself.

**Comment by hansemannn** [comment]
Closing for now, because the tinting is not part of the ti.map module and can be achieved using the above solutions. Thanks guys! 🚀
